version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
  app:
    image: whos_in_bot
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres@postgres:5432/whos_in_bot
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGDATABASE=whos_in_bot
